# for deployments of prerelease docs
[context.next]
  command = "make build"
  
  [context.next.environment]
  PRERELEASE = "true"
  ALGOLIA_INDEX_NAME = "dbt-next"
  
  [[headers]]
  for = "/*"
    [headers.values]
    X-robots-tag = "noindex"
